#!/bin/bash

find_bugs_golint() {
	basedir=$(pwd)
	cd $basedir
	for element in `find . -path ./.cache -prune -o -name "*.go"`; do
		gofmt -w ${basedir}/$element
	done
}

build_meta(){
    commit=`git log -1 --pretty="%H"`
    version="
    // Code generated by tool. DO NOT EDIT! \n
    package main\n
    //export VERSION ... \n
    const VERSION = \"$commit\" \n
    "
    echo  $version > version.go
}

find_bugs_golint $@

build_meta $@

go build -tags "h264enc"
